# Generated by Django 5.2.4 on 2025-07-20 11:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecipeModel",
            fields=[
                (
                    "recipe_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipe_name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "recipe_description",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                (
                    "recipe_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="recipes/%Y/%m/"
                    ),
                ),
                ("recipe_slug", models.SlugField(max_length=120, unique=True)),
                (
                    "recipe_type",
                    models.CharField(
                        choices=[
                            ("VEG", "Vegetarian"),
                            ("NON_VEG", "Non-Vegetarian"),
                            ("VEGAN", "Vegan"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recipes_master",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipe_type", "is_active"],
                        name="recipes_mas_recipe__575a0a_idx",
                    ),
                    models.Index(
                        fields=["created_at", "is_active"],
                        name="recipes_mas_created_8d238e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IngredientsModel",
            fields=[
                (
                    "ingredient_id",
                    models.UUIDField(
                        default=uuid.UUID("453f248d-d3b4-433d-be16-ef19c5e778d7"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="home.recipemodel",
                    ),
                ),
            ],
            options={
                "db_table": "ingredients",
            },
        ),
    ]
